services:
  - type: web
    name: ZIKO-MD
    env: node
    branch: main
    repo: https://github.com/Oyysreejan/ZIKO-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: ã€†Íğ™ğ¢ğ¤ğ¨-ğŒğğŸ‘€ğŸ¦‹ ËÍ¢Â»;ã€†Íğ™ğ¢ğ¤ğ¨-ğŒğğŸ‘€ğŸ¦‹ ËÍ¢Â»;https://i.imgur.com/7ZMfACG.mp4
      - key: ALWAYS_ONLINE
        value: true
      - key: AUTO_STATUS_VIEWS
        value: true
      - key: AUDIO_DATA
        value: ã€†Íğ™ğˆğŠğ-ğŒğƒğŸ‘€ğŸ¦‹ ËÍ¢Â»;zikoğŸ‘€ğŸ¦‹ ËÍ¢Â»;https://i.imgur.com/7ZMfACG.mp4
      - key: HANDLER
        value: /
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: CAPTION
        value: ã€†Íğ™ğˆğŠğ-ğŒğƒğŸ‘€ğŸ¦‹ ËÍ¢Â»ğŸŒˆ
      - key: STICKER_DATA
        value: ã€†Íğ™ğˆğŠğ-ğŒğƒğŸ‘€ğŸ¦‹ ËÍ¢Â»;zikoğŸ‘€ğŸ¦‹ ËÍ¢Â»
      - key: SUDO
        value: 917439382677
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
      - key: LOGS
        value: true 
